const express = require("express");
const router = express.Router();

const authRoutes = require("./auth");
const clientRoutes = require("./clientRoutes");
const projectRoutes = require("./projectRoutes");
const taskRoutes = require("./taskRoutes");
const uploadRoutes = require("./uploadRoutes");
const projectFileRoutes = require("./projectFileRoutes");
const roleRoutes = require("./roleRoutes");
const communityRoutes = require("./communityRoutes");
const postRoutes = require("./postRoutes");
const commentRoutes = require("./commentRoutes");
const feedRoutes = require("./feedRoutes");
const conversationRoutes = require("./conversationRoutes");
const messageRoutes = require("./messageRoutes");
const notificationRoutes = require("./notificationRoutes");
const emailRoutes = require("./emailRoutes");
const jobRoutes = require("./jobRoutes");
const adminRoutes = require("./adminRoutes");
const reportRoutes = require("./reportRoutes");
const searchRoutes = require("./searchRoutes");
const subscriptionRoutes = require("./subscriptionRoutes");
const timeTrackingRoutes = require("./timeTrackingRoutes");
const communityChatRoutes = require("./communityChatRoutes");
const dashboardAnalyticsRoutes = require("./dashboardAnalyticsRoutes");

router.use("/auth", authRoutes);
router.use("/clients", clientRoutes);
router.use("/search", searchRoutes);
router.use("/reports", reportRoutes);
router.use("/projects", projectRoutes);
router.use("/projects", taskRoutes);
router.use("/projects", projectFileRoutes);
router.use("/uploads", uploadRoutes);
router.use("/roles", roleRoutes);
router.use("/communities", communityRoutes);
router.use("/posts", postRoutes);
router.use("/comments", commentRoutes);
router.use("/conversations", conversationRoutes);
router.use("/messages", messageRoutes);
router.use("/notifications", notificationRoutes);
router.use("/email", emailRoutes);
router.use("/", jobRoutes);
router.use("/", feedRoutes);
router.use("/admin", adminRoutes);
router.use("/billing", subscriptionRoutes);
router.use("/time-tracking", timeTrackingRoutes);
router.use("/community-chat", communityChatRoutes);
router.use("/", dashboardAnalyticsRoutes);

module.exports = router;
